use_frameworks!

platform :ios, '13.0'

target 'MTACodable_Example' do
  pod 'MTACodable', :path => '../'
#  pod 'MTACodable', :git => 'https://github.com/daigewuwy/MyCodable.git'
  target 'MTACodable_Tests' do
    inherit! :search_paths

    
  end
end
